#!/bin/bash
## Run `bash <(curl -s https://raw.githubusercontent.com/JosiahKerley/hydrobot/master/other/setup-rpi)` from a fresh raspbian to setup

## Setup
apt-get update -y


## Set monitor to "always on"
sed -i 's/^BLANK_TIME=.*/BLANK_TIME=0/g' /etc/kbd/config


## Set autologin on terminal
sed -i 's/^1:2345:.*/1:2345:respawn:\/bin\/login -f pi tty1 <\/dev\/tty1 >\/dev\/tty1 2>&1/g'


## Change hostname to "hydrobot"
echo 'hydrobot' > /etc/hostname


## Start glances on start
echo glances >> /home/pi/.bashrc


## Extra apps
apt-get install -y htop iotop iftop tmux
pip install glances


## Install Hydrobot
mkdir -p /opt/hydrobot
git clone https://github.com/JosiahKerley/hydrobot /opt/hydrobot


## Setup updater
cat >> /etc/rc.local << EOF
sleep 5
if ping -c 5 8.8.8.8
then
  if [ ! -f /.firstboot ]
  then
    if update-hydrobot
    then
      touch /.firstboot
    fi
  fi
fi
EOF
