#!/bin/bash
## Run `sudo bash < <(curl -s https://raw.githubusercontent.com/JosiahKerley/hydrobot/master/other/setup-rpi)` from a fresh raspbian to setup

## Setup
apt-get update -y


## Set monitor to "always on"
sed -i 's/^BLANK_TIME=.*/BLANK_TIME=0/g' /etc/kbd/config


## Set autologin on terminal
sed -i '/^1:2345:.*/s/1:2345:.*/1:2345:respawn:\/bin\/login -f pi tty1 <\/dev\/tty1 >\/dev\/tty1 2>\&1/g' /etc/inittab


## Change hostname to "hydrobot"
echo 'hydrobot' > /etc/hostname


## Start glances on start
sed -i 's/.*glances.*//g' /home/pi/.bashrc
echo "flock -n /tmp/.login -c glances" >> /home/pi/.bashrc


## Extra apps
apt-get install -y htop iotop iftop tmux gcc python-dev python-pip redis-server
pip install psutil || pip install psutil --upgrade
pip install glances
pip install redis
pip install pyyaml


## Install Hydrobot
if [ -d /opt/hydrobot ]
then
  update-hydrobot
else
  mkdir -p /opt/hydrobot
  git clone https://github.com/JosiahKerley/hydrobot /opt/hydrobot
  cd /opt/hydrobot
  bash install
  mkdir -p /etc/hydrobot
  cat other/settings.yml > /etc/hydrobot/settings.yml
  cd -
fi


## Setup updater
cat >> /etc/rc.local << EOF
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi
sleep 5
if ping -c 5 8.8.8.8
then
  if [ ! -f /.firstboot ]
  then
    clear
    echo 'Updating HydRobot...'
    sleep 3
    if update-hydrobot
    then
      touch /.firstboot
    fi
  fi
fi
exit 0
EOF
