#!/bin/bash


## Setup cron
cat > /etc/cron.d/01-hydrobot << EOF
@reboot root flock -n /tmp/.hydrobot -c "hydrobot --daemon" >> /var/log/hydrobot
? ? ? ? ? root flock -n /tmp/.hydrobot -c "hydrobot --daemon" >> /var/log/hydrobot
EOF


## Update
./update
