#!/bin/bash


## Setup cron
cat > /etc/cron.d/01-hydrobot << EOF
@reboot root flock -n /tmp/.hydrobot -c "hydrobot --daemon" >> /var/log/hydrobot
? ? ? ? ? root flock -n /tmp/.hydrobot -c "hydrobot --daemon" >> /var/log/hydrobot
EOF


## Setup prereqs
if ! apt-get install -y python-redis || yum install -y python-redis
then
  echo Cannot install python redis!
  exit 1
fi


## Update
./update
