#!/bin/bash


## Setup cron
cat > /etc/cron.d/01-hydrobot << EOF
@reboot root flock -n /tmp/.hydrobot -c "hydrobot --daemon"
? ? ? ? ? root flock -n /tmp/.hydrobot -c "hydrobot --daemon"
EOF


## Update
./update
