#!/bin/bash


## Setup cron
cat > /etc/cron.d/01-hydrobot << EOF
@reboot root flock -n /tmp/.hydrobot -c "while ! service redis-server status | grep running; do sleep 5; done; hydrobot --daemon >> /var/log/hydrobot"
* * * * * root flock -n /tmp/.hydrobot -c "while ! service redis-server status | grep running; do sleep 5; done; hydrobot --daemon >> /var/log/hydrobot"
EOF


## Call install
if [ ! -d /etc/redis ]
then
  bash ./install
fi


## Install daemon
cat src/hydrobot.py > /usr/bin/hydrobot
chmod +x /usr/bin/hydrobot


## Updater
cat > /usr/bin/update-hydrobot << EOF
#!/bin/bash
cd /opt/hydrobot
git pull
bash ./update
cd -
EOF
chmod +x /usr/bin/update-hydrobot
