#!/bin/bash

if [ ! -f /etc/cron.d/01-hydrobot ]
then
  bash ./install
fi


## Install daemon
cat src/hydrobot.py > /usr/bin/hydrobot
chmod +x /usr/bin/hydrobot


## Updater
echo > /usr/bin/update-hydrobot << EOF
cd /opt/hydrobot
git pull
bash ./update
cd -
EOF
chmod +x /usr/bin/update-hydrobot
